apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: AWS_ACCESS_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: AWS_ACCESS_KEY_ID
             - name: AWS_SECRET_ACCESS_KEY
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: AWS_SECRET_ACCESS_KEY
             - name: S3_ENDPOINT
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: S3_ENDPOINT
             - name: NODE_ENV
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: NODE_ENV
             - name: RABBIT_URLS
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: RABBIT_URLS
             - name: MONGO_DB_URL
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: MONGO_DB_URL
             - name: POST_BUCKET
               valueFrom:
                 secretKeyRef:
                   name: files-myingram-production-config-secret
                   key: POST_BUCKET
