apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: RABBIT_URLS
               valueFrom:
                 secretKeyRef:
                   name: posts-production-config-secret
                   key: RABBIT_URLS
             - name: FILE_PROD_SERVICE
               valueFrom:
                 secretKeyRef:
                   name: posts-production-config-secret
                   key: FILE_PROD_SERVICE
             - name: NODE_ENV
               valueFrom:
                 secretKeyRef:
                   name: posts-production-config-secret
                   key: NODE_ENV
             - name: POSTS_DB_URL
               valueFrom:
                 secretKeyRef:
                   name: posts-production-config-secret
                   key: POSTS_DB_URL
