apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: CONNECT_PORT
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: CONNECT_PORT
             - name: FILES_TCP
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: FILES_TCP
             - name: PASSWORD_FOR_EMAIL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: PASSWORD_FOR_EMAIL
             - name: EMAIL_FOR_SENDING
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: EMAIL_FOR_SENDING
             - name: ACCESS_TOKEN
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: ACCESS_TOKEN
             - name: REFRESH_TOKEN
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: REFRESH_TOKEN
             - name: ACCESS_TOKEN_EXPIRATION
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: ACCESS_TOKEN_EXPIRATION
             - name: REFRESH_TOKEN_EXPIRATION
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: REFRESH_TOKEN_EXPIRATION
             - name: RECAPTCHA_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: RECAPTCHA_SECRET_KEY
             - name: BASE_URL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: BASE_URL
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: NODE_ENV
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: NODE_ENV
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: DATABASE_URL
             - name: FILE_PROD_SERVICE
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: FILE_PROD_SERVICE
             - name: PROFILE_PROD_SERVICE
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: PROFILE_PROD_SERVICE
             - name: RABBIT_URLS
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: RABBIT_URLS
             - name: GATE_PROFILE_GRPC_URL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: GATE_PROFILE_GRPC_URL
             - name: STRIPE_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: STRIPE_API_KEY
             - name: STRIPE_WEBHOOK_SECRET
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: STRIPE_WEBHOOK_SECRET
             - name: GATE_PAYMENTS_GRPC_URL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: GATE_PAYMENTS_GRPC_URL
             - name: POST_PROD_SERVICE
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: POST_PROD_SERVICE
             - name: ADMIN_LOGIN
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: ADMIN_LOGIN
             - name: ADMIN_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: ADMIN_PASSWORD
             - name: REDIS_HOST
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: REDIS_HOST
             - name: REDIS_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: REDIS_PASSWORD
             - name: REDIS_PORT
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: REDIS_PORT