apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: CONNECT_PORT
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: CONNECT_PORT
             - name: FILES_TCP
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: FILES_TCP
             - name: PASSWORD_FOR_EMAIL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: PASSWORD_FOR_EMAIL
             - name: EMAIL_FOR_SENDING
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: EMAIL_FOR_SENDING
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: gate-production-config-secret
                   key: DATABASE_URL
